version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.22
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - crt-symfony
  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm/
    ports:
      - "${PHP_PORT}:9001"
    networks:
      - crt-symfony
    volumes:
      - ./app:/var/www/crt_symfony_2
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php-fpm
    volumes:
      - ./app/public:/var/www/crt_symfony_2/public
      - ./logs/nginx:/var/log/nginx:cached
    networks:
      - crt-symfony

networks:
  crt-symfony: