version: '3'
services:
  mysql:
    container_name: ${MYSQL_HOST}
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - crt-symfony
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    ports:
      - "${PHP_PORT}:9001"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    networks:
      - crt-symfony
    volumes:
      - ./app/public:/var/www/crt_symfony_2/public
      - ./app/src:/var/www/crt_symfony_2/src
      - ./app/templates:/var/www/crt_symfony_2/templates
    depends_on:
      - mysql
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php-fpm
    volumes:
      - ./app/public:/var/www/crt_symfony_2/public
      - ./var/logs/nginx:/var/log/nginx:cached
    networks:
      - crt-symfony

networks:
  crt-symfony: